version: "3.9"
services:
  db:
    container_name: postgres.local
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_links
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /tmp/psqldata:/var/lib/postgresql/data
      - /tmp:/tmp

  adminer:
    container_name: adminers.local
    image: adminer
    restart: always
    ports:
      - "8080:8080"